// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urdqfhalajwmfcvfydzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZHFmaGFsYWp3bWZjdmZ5ZHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjA0MzAsImV4cCI6MjA2ODQzNjQzMH0.UqnZPLQ83EQ9tJ1ljgugKWv9n17fSzPgllz398QfWBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});